version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: '${CF_API_KEY}'
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/project-architect-2/files/5806486"
      EULA: "TRUE"
      MEMORY: "6G"
      VERSION: "1.20.1"
    volumes:
      - ./mcdata:/data
    restart: on-failure:3
