version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: '${CF_API_KEY}'
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/project-architect-2/files/5806486"
      EULA: "TRUE"
      MEMORY: "6G"
      VERSION: "1.20.1"
    volumes:
      - ./mcdata:/data
    restart: on-failure:3

  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: minecraft
      DEBUG: "true"
    depends_on:
      - minecraft

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor

  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.3}
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  mc-data: {}
  prometheus-tsdb: {}
  grafana-lib: {}
